name: strakly-backend
services:
  - name: strakly-backend
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 6
      success_threshold: 1
