export interface CurrencyInfo {
  country: string
  code: string
  symbol: string
  locale: string
}

export const COUNTRY_CURRENCY_MAP: Record<string, CurrencyInfo> = {
  "Afghanistan": { country: "Afghanistan", code: "AFN", symbol: "؋", locale: "fa-AF" },
  "Albania": { country: "Albania", code: "ALL", symbol: "L", locale: "sq-AL" },
  "Algeria": { country: "Algeria", code: "DZD", symbol: "د.ج", locale: "ar-DZ" },
  "Angola": { country: "Angola", code: "AOA", symbol: "Kz", locale: "pt-AO" },
  "Argentina": { country: "Argentina", code: "ARS", symbol: "$", locale: "es-AR" },
  "Armenia": { country: "Armenia", code: "AMD", symbol: "֏", locale: "hy-AM" },
  "Australia": { country: "Australia", code: "AUD", symbol: "A$", locale: "en-AU" },
  "Austria": { country: "Austria", code: "EUR", symbol: "€", locale: "de-AT" },
  "Azerbaijan": { country: "Azerbaijan", code: "AZN", symbol: "₼", locale: "az-AZ" },
  "Bahrain": { country: "Bahrain", code: "BHD", symbol: "BD", locale: "ar-BH" },
  "Bangladesh": { country: "Bangladesh", code: "BDT", symbol: "৳", locale: "bn-BD" },
  "Belarus": { country: "Belarus", code: "BYN", symbol: "Br", locale: "be-BY" },
  "Belgium": { country: "Belgium", code: "EUR", symbol: "€", locale: "nl-BE" },
  "Benin": { country: "Benin", code: "XOF", symbol: "CFA", locale: "fr-BJ" },
  "Bhutan": { country: "Bhutan", code: "BTN", symbol: "Nu", locale: "dz-BT" },
  "Bolivia": { country: "Bolivia", code: "BOB", symbol: "Bs", locale: "es-BO" },
  "Botswana": { country: "Botswana", code: "BWP", symbol: "P", locale: "en-BW" },
  "Brazil": { country: "Brazil", code: "BRL", symbol: "R$", locale: "pt-BR" },
  "Brunei": { country: "Brunei", code: "BND", symbol: "B$", locale: "ms-BN" },
  "Bulgaria": { country: "Bulgaria", code: "BGN", symbol: "лв", locale: "bg-BG" },
  "Burkina Faso": { country: "Burkina Faso", code: "XOF", symbol: "CFA", locale: "fr-BF" },
  "Burundi": { country: "Burundi", code: "BIF", symbol: "FBu", locale: "fr-BI" },
  "Cambodia": { country: "Cambodia", code: "KHR", symbol: "៛", locale: "km-KH" },
  "Cameroon": { country: "Cameroon", code: "XAF", symbol: "FCFA", locale: "fr-CM" },
  "Canada": { country: "Canada", code: "CAD", symbol: "C$", locale: "en-CA" },
  "Central African Republic": { country: "Central African Republic", code: "XAF", symbol: "FCFA", locale: "fr-CF" },
  "Chad": { country: "Chad", code: "XAF", symbol: "FCFA", locale: "fr-TD" },
  "Chile": { country: "Chile", code: "CLP", symbol: "$", locale: "es-CL" },
  "China": { country: "China", code: "CNY", symbol: "¥", locale: "zh-CN" },
  "Colombia": { country: "Colombia", code: "COP", symbol: "$", locale: "es-CO" },
  "Congo": { country: "Congo", code: "XAF", symbol: "FCFA", locale: "fr-CG" },
  "Costa Rica": { country: "Costa Rica", code: "CRC", symbol: "₡", locale: "es-CR" },
  "Croatia": { country: "Croatia", code: "EUR", symbol: "€", locale: "hr-HR" },
  "Cuba": { country: "Cuba", code: "CUP", symbol: "$", locale: "es-CU" },
  "Cyprus": { country: "Cyprus", code: "EUR", symbol: "€", locale: "el-CY" },
  "Czech Republic": { country: "Czech Republic", code: "CZK", symbol: "Kč", locale: "cs-CZ" },
  "Denmark": { country: "Denmark", code: "DKK", symbol: "kr", locale: "da-DK" },
  "Dominican Republic": { country: "Dominican Republic", code: "DOP", symbol: "RD$", locale: "es-DO" },
  "DR Congo": { country: "DR Congo", code: "CDF", symbol: "FC", locale: "fr-CD" },
  "Ecuador": { country: "Ecuador", code: "USD", symbol: "$", locale: "es-EC" },
  "Egypt": { country: "Egypt", code: "EGP", symbol: "E£", locale: "ar-EG" },
  "El Salvador": { country: "El Salvador", code: "USD", symbol: "$", locale: "es-SV" },
  "Eritrea": { country: "Eritrea", code: "ERN", symbol: "Nfk", locale: "ti-ER" },
  "Estonia": { country: "Estonia", code: "EUR", symbol: "€", locale: "et-EE" },
  "Eswatini": { country: "Eswatini", code: "SZL", symbol: "E", locale: "en-SZ" },
  "Ethiopia": { country: "Ethiopia", code: "ETB", symbol: "Br", locale: "am-ET" },
  "Fiji": { country: "Fiji", code: "FJD", symbol: "FJ$", locale: "en-FJ" },
  "Finland": { country: "Finland", code: "EUR", symbol: "€", locale: "fi-FI" },
  "France": { country: "France", code: "EUR", symbol: "€", locale: "fr-FR" },
  "Gabon": { country: "Gabon", code: "XAF", symbol: "FCFA", locale: "fr-GA" },
  "Gambia": { country: "Gambia", code: "GMD", symbol: "D", locale: "en-GM" },
  "Georgia": { country: "Georgia", code: "GEL", symbol: "₾", locale: "ka-GE" },
  "Germany": { country: "Germany", code: "EUR", symbol: "€", locale: "de-DE" },
  "Ghana": { country: "Ghana", code: "GHS", symbol: "GH₵", locale: "en-GH" },
  "Greece": { country: "Greece", code: "EUR", symbol: "€", locale: "el-GR" },
  "Guatemala": { country: "Guatemala", code: "GTQ", symbol: "Q", locale: "es-GT" },
  "Guinea": { country: "Guinea", code: "GNF", symbol: "FG", locale: "fr-GN" },
  "Haiti": { country: "Haiti", code: "HTG", symbol: "G", locale: "fr-HT" },
  "Honduras": { country: "Honduras", code: "HNL", symbol: "L", locale: "es-HN" },
  "Hungary": { country: "Hungary", code: "HUF", symbol: "Ft", locale: "hu-HU" },
  "Iceland": { country: "Iceland", code: "ISK", symbol: "kr", locale: "is-IS" },
  "India": { country: "India", code: "INR", symbol: "₹", locale: "en-IN" },
  "Indonesia": { country: "Indonesia", code: "IDR", symbol: "Rp", locale: "id-ID" },
  "Iran": { country: "Iran", code: "IRR", symbol: "﷼", locale: "fa-IR" },
  "Iraq": { country: "Iraq", code: "IQD", symbol: "ع.د", locale: "ar-IQ" },
  "Ireland": { country: "Ireland", code: "EUR", symbol: "€", locale: "en-IE" },
  "Israel": { country: "Israel", code: "ILS", symbol: "₪", locale: "he-IL" },
  "Italy": { country: "Italy", code: "EUR", symbol: "€", locale: "it-IT" },
  "Ivory Coast": { country: "Ivory Coast", code: "XOF", symbol: "CFA", locale: "fr-CI" },
  "Jamaica": { country: "Jamaica", code: "JMD", symbol: "J$", locale: "en-JM" },
  "Japan": { country: "Japan", code: "JPY", symbol: "¥", locale: "ja-JP" },
  "Jordan": { country: "Jordan", code: "JOD", symbol: "JD", locale: "ar-JO" },
  "Kazakhstan": { country: "Kazakhstan", code: "KZT", symbol: "₸", locale: "kk-KZ" },
  "Kenya": { country: "Kenya", code: "KES", symbol: "KSh", locale: "en-KE" },
  "Kuwait": { country: "Kuwait", code: "KWD", symbol: "KD", locale: "ar-KW" },
  "Kyrgyzstan": { country: "Kyrgyzstan", code: "KGS", symbol: "сом", locale: "ky-KG" },
  "Laos": { country: "Laos", code: "LAK", symbol: "₭", locale: "lo-LA" },
  "Latvia": { country: "Latvia", code: "EUR", symbol: "€", locale: "lv-LV" },
  "Lebanon": { country: "Lebanon", code: "LBP", symbol: "L£", locale: "ar-LB" },
  "Lesotho": { country: "Lesotho", code: "LSL", symbol: "L", locale: "en-LS" },
  "Liberia": { country: "Liberia", code: "LRD", symbol: "L$", locale: "en-LR" },
  "Libya": { country: "Libya", code: "LYD", symbol: "LD", locale: "ar-LY" },
  "Lithuania": { country: "Lithuania", code: "EUR", symbol: "€", locale: "lt-LT" },
  "Luxembourg": { country: "Luxembourg", code: "EUR", symbol: "€", locale: "fr-LU" },
  "Madagascar": { country: "Madagascar", code: "MGA", symbol: "Ar", locale: "mg-MG" },
  "Malawi": { country: "Malawi", code: "MWK", symbol: "MK", locale: "en-MW" },
  "Malaysia": { country: "Malaysia", code: "MYR", symbol: "RM", locale: "ms-MY" },
  "Maldives": { country: "Maldives", code: "MVR", symbol: "Rf", locale: "dv-MV" },
  "Mali": { country: "Mali", code: "XOF", symbol: "CFA", locale: "fr-ML" },
  "Malta": { country: "Malta", code: "EUR", symbol: "€", locale: "mt-MT" },
  "Mauritania": { country: "Mauritania", code: "MRU", symbol: "UM", locale: "ar-MR" },
  "Mauritius": { country: "Mauritius", code: "MUR", symbol: "₨", locale: "en-MU" },
  "Mexico": { country: "Mexico", code: "MXN", symbol: "MX$", locale: "es-MX" },
  "Moldova": { country: "Moldova", code: "MDL", symbol: "L", locale: "ro-MD" },
  "Mongolia": { country: "Mongolia", code: "MNT", symbol: "₮", locale: "mn-MN" },
  "Morocco": { country: "Morocco", code: "MAD", symbol: "MAD", locale: "ar-MA" },
  "Mozambique": { country: "Mozambique", code: "MZN", symbol: "MT", locale: "pt-MZ" },
  "Myanmar": { country: "Myanmar", code: "MMK", symbol: "K", locale: "my-MM" },
  "Namibia": { country: "Namibia", code: "NAD", symbol: "N$", locale: "en-NA" },
  "Nepal": { country: "Nepal", code: "NPR", symbol: "Rs", locale: "ne-NP" },
  "Netherlands": { country: "Netherlands", code: "EUR", symbol: "€", locale: "nl-NL" },
  "New Zealand": { country: "New Zealand", code: "NZD", symbol: "NZ$", locale: "en-NZ" },
  "Nicaragua": { country: "Nicaragua", code: "NIO", symbol: "C$", locale: "es-NI" },
  "Niger": { country: "Niger", code: "XOF", symbol: "CFA", locale: "fr-NE" },
  "Nigeria": { country: "Nigeria", code: "NGN", symbol: "₦", locale: "en-NG" },
  "North Macedonia": { country: "North Macedonia", code: "MKD", symbol: "ден", locale: "mk-MK" },
  "Norway": { country: "Norway", code: "NOK", symbol: "kr", locale: "nb-NO" },
  "Oman": { country: "Oman", code: "OMR", symbol: "OMR", locale: "ar-OM" },
  "Pakistan": { country: "Pakistan", code: "PKR", symbol: "Rs", locale: "ur-PK" },
  "Palestine": { country: "Palestine", code: "ILS", symbol: "₪", locale: "ar-PS" },
  "Panama": { country: "Panama", code: "PAB", symbol: "B/.", locale: "es-PA" },
  "Papua New Guinea": { country: "Papua New Guinea", code: "PGK", symbol: "K", locale: "en-PG" },
  "Paraguay": { country: "Paraguay", code: "PYG", symbol: "₲", locale: "es-PY" },
  "Peru": { country: "Peru", code: "PEN", symbol: "S/", locale: "es-PE" },
  "Philippines": { country: "Philippines", code: "PHP", symbol: "₱", locale: "en-PH" },
  "Poland": { country: "Poland", code: "PLN", symbol: "zł", locale: "pl-PL" },
  "Portugal": { country: "Portugal", code: "EUR", symbol: "€", locale: "pt-PT" },
  "Qatar": { country: "Qatar", code: "QAR", symbol: "QR", locale: "ar-QA" },
  "Romania": { country: "Romania", code: "RON", symbol: "lei", locale: "ro-RO" },
  "Russia": { country: "Russia", code: "RUB", symbol: "₽", locale: "ru-RU" },
  "Rwanda": { country: "Rwanda", code: "RWF", symbol: "RF", locale: "rw-RW" },
  "Saudi Arabia": { country: "Saudi Arabia", code: "SAR", symbol: "SAR", locale: "ar-SA" },
  "Senegal": { country: "Senegal", code: "XOF", symbol: "CFA", locale: "fr-SN" },
  "Serbia": { country: "Serbia", code: "RSD", symbol: "din", locale: "sr-RS" },
  "Sierra Leone": { country: "Sierra Leone", code: "SLE", symbol: "Le", locale: "en-SL" },
  "Singapore": { country: "Singapore", code: "SGD", symbol: "S$", locale: "en-SG" },
  "Slovakia": { country: "Slovakia", code: "EUR", symbol: "€", locale: "sk-SK" },
  "Slovenia": { country: "Slovenia", code: "EUR", symbol: "€", locale: "sl-SI" },
  "Somalia": { country: "Somalia", code: "SOS", symbol: "Sh", locale: "so-SO" },
  "South Africa": { country: "South Africa", code: "ZAR", symbol: "R", locale: "en-ZA" },
  "South Korea": { country: "South Korea", code: "KRW", symbol: "₩", locale: "ko-KR" },
  "South Sudan": { country: "South Sudan", code: "SSP", symbol: "SS£", locale: "en-SS" },
  "Spain": { country: "Spain", code: "EUR", symbol: "€", locale: "es-ES" },
  "Sri Lanka": { country: "Sri Lanka", code: "LKR", symbol: "Rs", locale: "si-LK" },
  "Sudan": { country: "Sudan", code: "SDG", symbol: "SDG", locale: "ar-SD" },
  "Sweden": { country: "Sweden", code: "SEK", symbol: "kr", locale: "sv-SE" },
  "Switzerland": { country: "Switzerland", code: "CHF", symbol: "CHF", locale: "de-CH" },
  "Syria": { country: "Syria", code: "SYP", symbol: "S£", locale: "ar-SY" },
  "Taiwan": { country: "Taiwan", code: "TWD", symbol: "NT$", locale: "zh-TW" },
  "Tajikistan": { country: "Tajikistan", code: "TJS", symbol: "SM", locale: "tg-TJ" },
  "Tanzania": { country: "Tanzania", code: "TZS", symbol: "TSh", locale: "sw-TZ" },
  "Thailand": { country: "Thailand", code: "THB", symbol: "฿", locale: "th-TH" },
  "Togo": { country: "Togo", code: "XOF", symbol: "CFA", locale: "fr-TG" },
  "Trinidad and Tobago": { country: "Trinidad and Tobago", code: "TTD", symbol: "TT$", locale: "en-TT" },
  "Tunisia": { country: "Tunisia", code: "TND", symbol: "DT", locale: "ar-TN" },
  "Turkey": { country: "Turkey", code: "TRY", symbol: "₺", locale: "tr-TR" },
  "Turkmenistan": { country: "Turkmenistan", code: "TMT", symbol: "T", locale: "tk-TM" },
  "UAE": { country: "UAE", code: "AED", symbol: "AED", locale: "ar-AE" },
  "Uganda": { country: "Uganda", code: "UGX", symbol: "USh", locale: "en-UG" },
  "Ukraine": { country: "Ukraine", code: "UAH", symbol: "₴", locale: "uk-UA" },
  "United Kingdom": { country: "United Kingdom", code: "GBP", symbol: "£", locale: "en-GB" },
  "United States": { country: "United States", code: "USD", symbol: "$", locale: "en-US" },
  "Uruguay": { country: "Uruguay", code: "UYU", symbol: "$U", locale: "es-UY" },
  "Uzbekistan": { country: "Uzbekistan", code: "UZS", symbol: "сўм", locale: "uz-UZ" },
  "Venezuela": { country: "Venezuela", code: "VES", symbol: "Bs", locale: "es-VE" },
  "Vietnam": { country: "Vietnam", code: "VND", symbol: "₫", locale: "vi-VN" },
  "Yemen": { country: "Yemen", code: "YER", symbol: "YR", locale: "ar-YE" },
  "Zambia": { country: "Zambia", code: "ZMW", symbol: "ZK", locale: "en-ZM" },
  "Zimbabwe": { country: "Zimbabwe", code: "ZWL", symbol: "Z$", locale: "en-ZW" },
}

export function getCurrencyFromCountry(country: string): CurrencyInfo {
  return COUNTRY_CURRENCY_MAP[country] || { country, code: "USD", symbol: "$", locale: "en-US" }
}

export function getCurrencySymbol(currencyCode: string): string {
  const entry = Object.values(COUNTRY_CURRENCY_MAP).find(c => c.code === currencyCode)
  return entry?.symbol || currencyCode
}
