// System Level Permissions (Super Admin)
export enum SystemPermissions {
  ADMIN_CREATE = 'ADMIN_CREATE',
  ADMIN_READ = 'ADMIN_READ',
  ADMIN_UPDATE = 'ADMIN_UPDATE',
  ADMIN_DELETE = 'ADMIN_DELETE',
  GYM_READ_ALL = 'GYM_READ_ALL',
  GYM_UPDATE_ANY = 'GYM_UPDATE_ANY',
  GYM_DELETE_ANY = 'GYM_DELETE_ANY',
}

// Gym Level Permissions
export enum GymPermissions {
  GYM_MANAGE = 'GYM_MANAGE',
  TRAINER_CREATE = 'TRAINER_CREATE',
  TRAINER_READ = 'TRAINER_READ',
  TRAINER_UPDATE = 'TRAINER_UPDATE',
  TRAINER_DELETE = 'TRAINER_DELETE',
  TRAINER_ASSIGN = 'TRAINER_ASSIGN',
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  DIET_PLAN_CREATE = 'DIET_PLAN_CREATE',
  DIET_PLAN_READ = 'DIET_PLAN_READ',
  DIET_PLAN_UPDATE = 'DIET_PLAN_UPDATE',
  DIET_PLAN_DELETE = 'DIET_PLAN_DELETE',
  EXERCISE_PLAN_CREATE = 'EXERCISE_PLAN_CREATE',
  EXERCISE_PLAN_READ = 'EXERCISE_PLAN_READ',
  EXERCISE_PLAN_UPDATE = 'EXERCISE_PLAN_UPDATE',
  EXERCISE_PLAN_DELETE = 'EXERCISE_PLAN_DELETE',
  PROGRESS_READ = 'PROGRESS_READ',
  PROGRESS_UPDATE = 'PROGRESS_UPDATE',
  ANNOUNCEMENT_CREATE = 'ANNOUNCEMENT_CREATE',
  ANNOUNCEMENT_READ = 'ANNOUNCEMENT_READ',
  ANNOUNCEMENT_UPDATE = 'ANNOUNCEMENT_UPDATE',
  ANNOUNCEMENT_DELETE = 'ANNOUNCEMENT_DELETE',
  REWARD_CREATE = 'REWARD_CREATE',
  REWARD_READ = 'REWARD_READ',
  REWARD_UPDATE = 'REWARD_UPDATE',
  REWARD_DELETE = 'REWARD_DELETE',
  SUCCESS_STORY_CREATE = 'SUCCESS_STORY_CREATE',
  SUCCESS_STORY_READ = 'SUCCESS_STORY_READ',
  SUCCESS_STORY_APPROVE = 'SUCCESS_STORY_APPROVE',
  SUBSCRIPTION_READ = 'SUBSCRIPTION_READ',
  SUBSCRIPTION_MANAGE = 'SUBSCRIPTION_MANAGE',
  GOAL_CRUD = 'GOAL_CRUD',
  HABIT_CRUD = 'HABIT_CRUD',
  TASK_CRUD = 'TASK_CRUD',
  EXERCISE_LOG = 'EXERCISE_LOG',
  DIET_LOG = 'DIET_LOG',
  FRIEND_MANAGE = 'FRIEND_MANAGE',
  CHALLENGE_MANAGE = 'CHALLENGE_MANAGE',
}

export const AllPermissions = { ...SystemPermissions, ...GymPermissions };

export type PermissionType = SystemPermissions | GymPermissions;
